services:
    app:
        container_name: laravel_app_filament
        working_dir: /var/www/html
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: /var/www/html/backend-myapp-v2/
              target: /var/www/html/public/storage
            - type: bind
              source: /var/www/html/backend-myapp-v2/storage/app/public/
              target: /var/www/html/public/storage
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    web:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8100:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    dbdata:
